services:
  turnos_medicos_db:
    image: postgres:15
    container_name: turnos_medicos_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
      POSTGRES_DB: turnos_medicos_db
    ports:
      - "5532:5432"
    volumes:
      - turnos_medicos_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  adminer:
    image: adminer
    container_name: turnos_medicos_adminer
    restart: unless-stopped
    ports:
      - "8088:8080"
    environment:
      ADMINER_DEFAULT_SERVER: turnos_medicos_db
    depends_on:
      - turnos_medicos_db

  turnos_medicos_app:
    build:
      context: .
    container_name: turnos_medicos_app
    restart: unless-stopped
    environment:
      DB_HOST: turnos_medicos_db
      DB_PORT: 5432
      DB_NAME: turnos_medicos_db
      DB_USER: user
      DB_PASSWORD: user123
    ports:
      - "8080:8080"
    depends_on:
      - turnos_medicos_db

volumes:
  turnos_medicos_data:
